services:
  app:
    build: .
    platform: linux/arm64
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/code
    env_file:
      - .env
